language: node_js
node_js:
  - "4"
  - "6"
env:
  - CXX=g++-4.8
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
install:
  - npm install uglify-js trireme
  - sudo apt-get -y install qt55[QTPACKAGE]
script:
  - source /opt/qt55/bin/qt55-env.sh
  - ant test
branches:
  only:
    - master
    - development
sudo: required
dist: precise
