language: node_js
node_js:
  - "4"
  - "6"
  - "8"
env:
  - CXX=g++-4.8

before_install:
  # Qt5
  - sudo apt-get clean
  - sudo add-apt-repository ppa:beineri/opt-qt562-trusty
  - sudo apt-get update

install:
   # Qt5
  #- yes | sudo apt-get install --yes qt55base qt55imageformats qt55svg qtdeclarative5-dev
  - source /opt/qt56/bin/qt56-env.sh
  - npm install
before_script:
  - QTDIR="/opt/qt56"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt56/bin/qt56-env.sh
script:
  - ant test
branches:
  only:
    - master
    - development
sudo: required
dist: precise
