language: node_js
node_js:
  - "4"
  - "6"
  - "8"
env:
  - CXX=g++-4.8
before_install:
  #- sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  #- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  #- sudo apt-get update -qq
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update
install:
  #- sudo apt-get -y install qt55[QTPACKAGE]
  #- sudo apt-get install qt5-default
  - sudo apt-get install qt58base qt58svg qt58charts-no-lgpl qt58xmlpatterns
  - source /opt/qt58/bin/qt58-env.sh
  - npm install
script:
  - source /opt/qt55/bin/qt55-env.sh
  - ant test
branches:
  only:
    - master
    - development
sudo: required
dist: precise
