language: node_js
node_js:
  - "4"
  - "6"
  - "8"
env:
  - CXX=g++-4.8
before_install:
  # Qt
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
install:
  # Qt
  - sudo apt-get -y install qt55[QTPACKAGE]
  - sudo apt-get -y install qmlscene qt5-default
  - npm install
before_script:
  #- QTDIR="/opt/qt55"
  #- QTBIN="/opt/qt55/bin"
  #- PATH="$QTDIR/bin:$PATH"
script:
  #- source /opt/qt55/bin/qt55-env.sh
  #- export QT_QPA_PLATFORM=offscreen
  - ant test
  #- cd qt
  #- which qmake
  #- which qmlscene
  #- /usr/bin/qmake -query
  # QFontDatabase: Cannot find font directory /usr/lib/x86_64-linux-gnu/fonts - is Qt installed correctly?
  #- sudo ln -s /usr/share/fonts /usr/lib/x86_64-linux-gnu/fonts
  # /usr/bin/qmlscene NodeunitRun.qml -I ../FileReader/imports/
  #- cd qt
  #- ant test.qt.nodeunit
branches:
  only:
    - master
    - development
sudo: required
#dist: precise
