language: node_js
node_js:
  - "4"
  - "6"
  - "8"
env:
  - CXX=g++-4.8
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get -y install qt55[QTPACKAGE]
  - npm install
script:
  - source /opt/qt55/bin/qt55-env.sh
  - ant test
branches:
  only:
    - master
    - development
sudo: required
dist: precise
