language: node_js
node_js:
  - "4"
  - "6"
  - "8"
env:
  - CXX=g++-4.8
before_install:
  # Qt
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
install:
  # Qt
  - sudo apt-get -y install qt55[QTPACKAGE]
  
  - npm install
before_script:
  #- QTDIR="/opt/qt55"
  #- QTBIN="/opt/qt55/bin"
  #- PATH="$QTDIR/bin:$PATH"
  #- source /opt/qt55/bin/qt55-env.sh
script:
  #- source /opt/qt55/bin/qt55-env.sh
  - xvfb-run make test
  - ant test
  - cd qt
  #- ant test.qt.nodeunit
branches:
  only:
    - master
    - development
sudo: required
#dist: precise
